image: node:22-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .svelte-kit/

before_script:
  - npm ci --prefer-offline --no-audit

stages:
  - lint
  - type-check
  - build

lint:
  stage: lint
  script:
    - npx prettier --check 'src/**/*.{svelte,ts,json}' 'README.md'
    - npx eslint 'src/**/*.{ts,svelte}'
  allow_failure: false

type-check:
  stage: type-check
  script:
    - npx svelte-kit sync
    - npx svelte-check --tsconfig ./tsconfig.json
  allow_failure: false

build:
  stage: build
  script:
    - npm run build
  allow_failure: false
